config/routes.rb
SocialKarma::Application.routes.draw do

  get "welcome/index"

  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get 'users/:id/edit' => 'users#edit', :as => :edit_user
  patch 'users/:id' => 'users#update', :as => :user
  get 'users/:id' => 'users#show'
  delete 'users/:id' => 'users#destroy'

  get '/auths' => 'auths#new', :as => :new_auth
  post '/auths' => 'auths#create'
  delete '/auths' => 'auths#destroy'  

  root 'welcome#index'

end

app/models/user.rb
require 'bcrypt'


class User
  include Mongoid::Document

  attr_accessor :password

  field :name, type: String
  field :email, type: String
  field :username, type: String
  field :rating, type: String
  field :salt, type: String
  field :hashed_password, type: String


 def authenticated? password
 	self.hashed_password ==
 	BCrypt::Engine.hash_secret(password, self.salt)
 end

 before_save :hash_stuff

 private 
 def hash_stuff
 	self.salt = BCrypt::Engine.generate_salt
 	self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
 	self.password = nil
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user 
  	if session[:user_id]
  		User.find_by(id:session[:user_id])
  	end
  end 

  def authenticate_user
  	redirect_to auths_path undless current_user
  end



end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController

	 def new 
	 	if current_user
	 		redirect_to users_path
	 	else
	 		@user = User.new
		end
	end

	def create 
		user = User.find_by(username: params[:user][:username])
		if user && user.authenticated?(params[:user][:password])
			session[:user_id] = user.id
			redirect_to users_path
		else
			flash[:notice] = "You are not logged in! I bet you're sad."
			redirect_to new_auth_path
		end
	end


	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else 
			render action: "new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to action: "index"
		else
			render action: "new"
		end
	end

		def show
			@user = User.find(params[:id])
		end

		def destroy 
			@user = User.find(params[:id])
				@user.destroy
				redirect_to action: "index"
		end



	private
	def user_params
		params.require(:user).permit(
			:name, :username, :password, :email, :rating)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@home_page = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auths/new.html.erb
	
	<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6 login">
	<h1>Log In</h1>
	<%= form_for @user, {url: "/auths", method:"post"} do |user|%>
	<%= user.text_field :username, :placeholder => "Your username", class: "form-control" %><br>
	<%= user.password_field :password, :placeholder => "Your password", class: "form-control" %><br>
	<%= user.submit "Log In", class: "btn btn-info" %>

		<p class="script"><%= flash[:notice] %></p>

	<%end%>
	</div>
	<div class="cold-md-3"></div>
	</div>

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialKarma</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
      <body>
        <div class="overlay"></div>
        <div class="row">
        <div class ="container-fluid">
         <div class="row above">
            <div class="col-md-2">
                <%=link_to "Karma", root_path, class: "navbar-brand" %>
            </div>
            <div class="col-md-2"></div>

            <!-- <div class="col-md-3"> -->
                <%= current_user ? "Hello #{current_user.name}" : link_to('Sign Up', users_new_path, {class: "btn btn-large btn-success col-md-2"}) %>

            <div class = "col-md-1"></div>
            <!-- </div> -->

            <!-- div class="col-md-3"> -->
              <% if current_user %>
                <%=button_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete, class: "btn btn-large btn-primary col-md-2 out"} %>
              <% else %>
                <%= link_to 'Log In', new_auth_path, {class: "btn btn-lage btn-info col-md-2"} %>
              <% end %>
          <!--   </div> -->
              <div class="col-md-1"></div>

              <div class="col-md-2 greybkg"></div>
           </div>
      </div>
</div>

              <%= yield %>



</body>
</html>










<!--   <header>
 -->    <%#=link_to "Karma", root_path, class: "navbar-brand" %>
    <%#= current_user ? "Hello #{current_user.name}" : link_to('Sign Up', users_new_path, {class: "btn btn-large btn-success top-btns"}) %>
<!-- 	 <% if current_user %>
				<%=button_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete, class: "btn btn-large btn-primary top-btns"} %>
    <% else %>
				<%= link_to 'Log In', new_auth_path, {class: "btn btn-lage btn-info top-btns"} %>
	 <% end %> -->
<!--   </header>
 -->  
 <!--  <%= yield %>
   
</div>

<div class="overlay"></div>

</body>
</html> -->

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>

<%= form_for @user do |f| %>

	<div>
		<%=f.label :name, "Name" %>
		<%=f.text_field :name %>
	</div>

	<div>
		<%= f.label :username, "Username" %>
		<%= f.text_field :username %>
	</div>

	<div>
		<%= f.label :email, "Email" %>
		<%= f.text_field :email %>
	</div>

	<div>
		<%= f.label :rating, "Rating" %>
		<%= f.text_field :rating %>
	</div>



	 <%=f.submit %>

	<% end %>

app/views/users/index.html.erb
<h1>Trustees!</h1>
<table class="table table-hover">

	<thead>
		<tr>
			<th><strong>NAME</strong></th>
			<th>USERNAME</th>
			<th>EMAIL</th>
			<th>RATING</th>
		</tr>
	</thead>
	<tbody> 
		<% @users.each do |user| %>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.username %></td>
				<td><%= user.email %></td>
				<td><%= user.rating %></td>
				<td><%= link_to 'Edit', edit_user_path(user), action: 'edit' %></td>
				<td><%= link_to 'Delete', user_path(user), method: :delete %></td>
				<td><%= link_to 'Show', user_path(user) %></td>

			</tr>

		<% end %>
	</tbody>
</table>


<%=link_to 'Sign Up', users_new_path, {class: "btn btn-large btn-primary"} %>
<%=link_to 'Log In', new_auth_path, {class: "btn btn-lage btn-primary"} %>
<%=button_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete} %>

<%= current_user ? current_user.name : "You are not logged in" %>

app/views/users/new.html.erb
<div class="row">
<div class="col-md-3"></div>
<div class = "signup">
<h1>Sign Up!</h1>

<%=form_for @user do |f| %>

	<%=f.text_field :name, :placeholder => "Enter Your Name", class: "form-control" %><br>
	<%=f.text_field :username, :placeholder => "Enter Your Username", class: "form-control"  %><br>
	<%=f.text_field :email, :placeholder => "Enter Your Email", class: "form-control"  %><br>
	<%=f.text_field :rating, :placeholder => "Enter Your Social Karma", class: "form-control"  %><br>
	<%=f.password_field :password, :placeholder => "Enter Your Password", class: "form-control"  %><br>
	<%=f.submit "Create New Account" %>
</div>
<% end %>

<%=button_to "Back", {:controller => 'users', :action => 'index'}, {:method => :get} %>

app/views/users/show.html.erb
<h2>Social Karma Stars</h2>

<%= form_for @user do |f| %>

	<div>
		<h3>NAME</h3>
	<%= @user.name %>
</div>

	<div>
		<h3>USERNAME</h3>
		<%= @user.username %>
	</div>

	<div>
		<h3>EMAIL</h3>
		<%= @user.email %>
	</div>

	<div>
		<h3>RATING</h3>
		<%= @user.rating %>
	</div>


	<% end %>

	<%=button_to "Back", {:controller => 'users', :action => 'index'}, {:method => :get} %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialKarma</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
      <body>




<div class="col-md-3 Dan">
                <div class="thumbnail">
                  <%=image_tag("danbeer.jpg", class: "img thumbnail", alt: "DAN") %>
                <div class="caption">
                  <h3>Dan</h3>
                  <p>Treat Yo' Self</p>
                  <p class="quote">"Dan brings Korean treats every week!"</p>
                  <p class="quote">10</p>
                </div>
              </div>
            </div>

            <div class="col-md-3 Jay">
                <div class="thumbnail">
                  <%=image_tag("jayAZ.jpg", class: "img thumbnail", alt: "JAY") %>
                <div class="caption">
                  <h3>Jay</h3>
                  <p>Lover not a Fighter </p>
                  <p class="quote">"Jay Borrowed my car and brought it back in great shape!"</p>
                  <p class="quote">10</p>

                </div>
              </div>
            </div>


            <div class="col-md-3 Tyson">
                <div class="thumbnail">
                  <%=image_tag("tyson.jpg", class: "img thumbnail", alt: "TYSON") %>
                <div class="caption">
                  <h3>MIKE TYSON</h3>
                  <p>Fighter not a Lover</p>
                  <p class="quote">"When Jesus comes back, these crazy, greedy, capitalistic men are gonna kill him again."</p></br>
                  <p class="quote">0</p>

                </div>
              </div>
            </div>

    


            <div class="col-md-3 Cage">
                <div class="thumbnail">
                  <%=image_tag("cage.jpg", class: "img thumbnail", alt: "CAGE") %>
                <div class="caption">
                  <h3>NIC CAGE</h3>
                  <p>Not Enough Terrible Movies to Get Him Out of Debt</p>
                  <p class="quote">"Did not pay his rent for 6 months."</p></br>
                  <p class="quote">0</p>

                </div>
              </div>
            </div>

 
            <div class="col-md-3 Bieber">
                <div class="thumbnail">
                  <%=image_tag("jb.jpg", class: "img thumbnail", alt: "JUSTIN") %>
                <div class="caption">
                  <h3>JUSTIN BIEBER</h3>
                  <p></p>
                  <p class="quote">"Borrowed my car and stole it."</p></br>
                  <p class="quote">0</p>

                </div>
              </div>
            </div>









</body>
</html>